[package]
name = "dm"
version = "0.2.1-alpha"
license = "MIT"
edition = "2024"

[dependencies]
chacha20poly1305 = "0.10.1"
hkdf = "0.12.4"
local-ip-address = "0.6.10"
sha2 = "0.10.9"
x25519-dalek = "2.0.1"
